### ISSUE TITLE
merge users date displays for once only courses

### ISSUE THREAD

**Issue by bkbatch** [gchlol/moodle-tool_mergeusers#4]
When merging users, the portfolio check has shown that once off courses do not update with the latest completion. There is a use case where an employee has had to recomplete a once only course and workplace relations has requested all completion dates. 

The portfolio needs to update with the latest completion and we need to keep a record of all previous completions in the database - users are concerned about deleting profiles and losing all of this data.

Tickets:
- G5T-D4T-18RG
- DRH-RLH-G7PR

**Comment by NickLambellGCH** [comment]
Comment from primary ticket:
> It looks like the 'merge to' user already had course completion records for a number of courses, likely due to being enrolled automatically. In these cases, even though the 'merge to' user doesn't have an actual completion timestamp, the 'merge from' record is completely ignored to prevent duplicate record errors and is deleted.
>
> From the merge logs for 'course_completions' below we can see that a number of course completion records that belonged to the 'merge from' user were deleted then only some moved over.
>
> Logs Link: https://wmlol.wmhhs.health.qld.gov.au/admin/tool/mergeusers/log.php?id=41.
> Logs 'course_completions' Content:
"DELETE FROM mdl_course_completions WHERE id IN (929825, 929917, 929964, 930009, 930026, 930052, 930066, 930080, 930098)",
"UPDATE mdl_course_completions SET userid = '16340' WHERE id IN (929839, 929853, 929867, 929881, 929895, 929978, 929995, 931880, 981867, 931918, 932029)",
